### DISCUSSION TITLE
Custom Layout but maintain markdown

### DISCUSSION THREAD

**Discussion by kyoukhana** [nuejs/nue#339] [General]
In layout.html.  How can make my custom layout so that it will read the markdown.md vs editing in html

```
<header>
  <nav aria-label="navigation"><a href="/">Emma Test</a> <a href="/contact/">Contact</a></nav>
</header>
```

The Emma Test should come from

site.yaml

But currently Its coming from the HTML.  Do I have to add any tags to make Emma Test come from the Markdown

**Comment by nobkd** [comment]
Hello, I don't quite understand your issue.
Can you please try to rephrase it, or explain it in more detail? Maybe, adding an example helps with this. Thank you.

**Reply by kyoukhana** [reply]
I just updated the question.  I forgot to put the code block

**Comment by nobkd** [comment]
Ok. I will now write out, what I think you mean with your description, and you can tell me, if that's what you want, or not.

You want, that the `title` is the H1 / title from the markdown file, and want to just add this to maybe a collection and render all the items in the collection as a navigation.

---

WIP example:

E.g. You have this files with this code:

- site.yaml
  ```yaml
  content_collection: .
  collection_name: pages
  ```
- index.md
  ```md
  ----
  title: Emma Test
  cat:
    - header: 0
  ---
  ```
- contact.md
  ```md
  ----
  cat:
    - header: 1
  ---
  
  # Contact
  ```

`layout.html`
```html
<header>
  <nav><link-collection catname="header" :pages /></nav>
</header>

<a @name="link-collection" :for="el in items" href="{base}{el.url}"
    aria-selected="{el.url == url || el.url + 'index.html' == url}">
    {el.title}
    <script>
        constructor({ catname, pages }) {
            pages.forEach(page => page.url = page.url.replace(/\/index.html$/i, '/'))
            this.items = pages
                .filter(page => Object.keys(page.cat ?? {}).includes(catname))
                .sort((a, b) => a.cat[catname] - b.cat[catname])
        }
    </script>
</a>
```

I haven't tested it currently, I'll check it in a while!

Issues with this approach is, that you might need another collection later on, and I'm not sure, if Nue currently supports multiple collections (See #145). It's possible, it was added recently, but I haven't checked it yet.


> [!Note]
> It might even be easier with some new components now, but I have also not checked that yet.

---

Alternative, but similar idea: add a list of **only paths** to the `site.yaml` and search through the `pages` collection with the paths, and the rest is mostly the same.

Then you can set the order simpler and avoid putting information about the order in all the used files all over the project.

Edit: I think this approach is the better one then, will try to provide a usable example, shortly.
Note: Need to do some other stuff, will do this in maybe half an hour.

**Comment by kyoukhana** [comment]
Kinda of but how can we retain getting the site name from the default site.yaml.  Currently in the file we have this

```
header:
  navigation:
    - Emma Bennet: /
    - Contact: /contact/
```

There has to be a way to get these values with a custom layout header

**Comment by nobkd** [comment]
```html
<!--layout.html-->

<header>
    <link-collection :arr="header.navigation" :pages />
</header>

<nav @name="link-collection">
    <a :for="el in items" href="{base}{el.url}" :bind="selected(el.url, url)">
        {el.title}
    </a>
    <script>
        selected(pageurl, url) {
            return pageurl == url || pageurl + 'index.html' == url ? { 'aria-selected': true } : {}
        }
        constructor({ arr, pages }) {
            const els = {}
            pages.forEach(page => {
                page.url = page.url.replace(/\/index\.html$/i, '/')
                els[page.url] = page

            })
            this.items = arr.map(val => els[val])
        }
    </script>
</nav>

```

```yaml
# site.yaml

content_collection: .
collection_name: pages

header:
  navigation:
    - /
    - /contact/

```

When I put this in the simple-blog example, and remove the `content_collection: blog` from `index.md` this works for the front page, but not the other pages, and it seems like you can't have a second collection (#145). I currently don't have the nerve and time to follow this further, maybe you can use this as a start. Good luck.

![grafik](https://github.com/user-attachments/assets/13e16882-5761-425f-8ec5-36ff039d081a)
![grafik](https://github.com/user-attachments/assets/e1c81799-11c7-431f-b8cd-779eca360eac)

**Reply by kyoukhana** [reply]
Thank You for the help

**Comment by kyoukhana** [comment]
The default site.yaml is like this In your layout you can call this:

```
<head>
  <script src="https://kit.fontawesome.com/d591cda822.js" crossorigin="anonymous"></script>
</head>
<header>
  {title_template}
  </header>
  ```

```
globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true

title_template: "Emma Bennet / %s"
og_image: /img/og_emma.png
author: Emma Bennet
favicon: /img/favicon.jpg
description: Minimalist, designer, and UX developer
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /img/og.jpg


header:
  navigation:
    - Emma Bennet: /
    - Contact: /contact/

footer:
  copyright:
    - © Emma Bennet: /

  social:
    - image: /img/twitter.svg
      url: //x.com/tipiirai
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/nuejs/
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/tipiirai
      alt: LinkedIn profile
      size: 22 x 22
```
