### DISCUSSION TITLE
How to Deploy My Nue.js Project on GitHub or Other Platforms?

### DISCUSSION THREAD

**Discussion by Hwayeeon** [nuejs/nue#436] [Q&A]
Hi, is it possible to deploy my Nue.js project on GitHub? And if not, could you please guide me on how to deploy it to a different platform?

**Comment by nobkd** [comment]
> [!Note]
> I didn't test this yet with the latest release.

If you want to publish to github pages, something like the following script should work:

If you deploy to a sub-direcory, e.g. `yourname.github.io/someproject`, you'll have to add `--base /someproject` or `-B /someproject` or add `base: /someproject` to an env file, for prod, e.g. `src/prod.yaml` and use `-e src/pub.yaml` to your build command, so the paths to the scripts, etc, are built correctly.

```yaml
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    paths: ["src/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build
        run: bun run build
        # e.g. nue build -pr src

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "src/.dist/prod"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Please ask if you need more help with this, or you meant to ask something different with your question :)
