### DISCUSSION TITLE
Did a todo app

### DISCUSSION THREAD

**Discussion by bartonhammond** [nuejs/nue#454] [Show and tell]
Learned a lot - got to start somewhere ;) 

I tried to get it on GitHub Pages but didn't work - [https://bartonhammond.github.io/nue-todo/](https://bartonhammond.github.io/nue-todo/) - I just put the `.dist/prod` into `/docs` and published from branch.  If someone could tell me why that fails, I'd try again. 

Here's the source: [https://github.com/bartonhammond/nue-todo](https://github.com/bartonhammond/nue-todo)

<img width="972" alt="Screenshot 2025-01-22 at 7 25 24 PM" src="https://github.com/user-attachments/assets/14f76c40-3954-4d0c-9289-ce9aa74d6f7c" />

**Comment by nobkd** [comment]
Try adding `--base /nue-todo` to your build command.
I'll have to check, if that still works properly,  but you can give it a try first if you want to.
I'll take a look tomorrow I guess.

**Reply by bartonhammond** [reply]
I built as `nue build --production --base /nue-todo` - looks the same in the `console` on GH

<img width="1505" alt="Screenshot 2025-01-22 at 9 03 53 PM" src="https://github.com/user-attachments/assets/70ab01d2-ba43-4087-bb16-fae7dfb39e27" />

**Comment by bartonhammond** [comment]
I updated to  from `1.1.42` to `1.2.0` and built again and the only change was in `index.html` with `date-updated`

**Reply by nobkd** [reply]
Sorry, I was in the wrong discussion, when writing a moment ago.

Was about the other way around, that bun changed some defaults, that may or may not have broken something in nue. I'm going to investigate, in a bit though

**Comment by nobkd** [comment]
Try making the following import relative (additionally to having the base option): `import { $ } from '/@nue/view-transitions.js'` -> `import { $ } from '../@nue/view-transitions.js'` it's not pretty, but should work for your spa.

I guess, the `base` option needs some love, to make components' js imports also work properly, when build to a different directory, and not just the ones in html


I would've also pointed you to the source code of the first todo app by nue, but it doesn't seem to exist anymore in this organization. (Here's the still deployed variant: https://nuejs.org/todomvc/)

**Comment by bartonhammond** [comment]
I've love to see the source for that `todomvc`.  I've built the todo example using their ToDo site provided template w/ the css but I didn't want to go that route with `nue` as I am terrible w/ css. It's black magic to me.  I've studied it and taken courses and worked with it extensively.  then 3 months later i can't remember how it works.  

Anyway - I did as you suggested... `  import { $ } from '../@nue/view-transitions.js' ` 

I assume that the site works fine with a local http server it should work on GH so I tried this
```
nue-todo$ cd docs
docs$ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [23/Jan/2025 09:04:57] "GET / HTTP/1.1" 200 -
::1 - - [23/Jan/2025 09:04:57] code 404, message File not found
::1 - - [23/Jan/2025 09:04:57] "GET /nue-todo/@nue/mount.js HTTP/1.1" 404 -
::1 - - [23/Jan/2025 09:04:57] code 404, message File not found
::1 - - [23/Jan/2025 09:04:57] "GET /nue-todo/@nue/view-transitions.js HTTP/1.1" 404 -
::1 - - [23/Jan/2025 09:04:57] code 404, message File not found
::1 - - [23/Jan/2025 09:04:57] "GET /img/avatar-rounded.jpg HTTP/1.1" 404 -
```
I also tried w/ `simple-blog` and get this:
```
prod$ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [23/Jan/2025 09:09:46] "GET / HTTP/1.1" 200 -
::1 - - [23/Jan/2025 09:09:46] code 404, message File not found
::1 - - [23/Jan/2025 09:09:46] "GET /simple-blog/@nue/view-transitions.js HTTP/1.1" 404 -
```

**Reply by nobkd** [reply]
The --base option is, to prepend links with the path provided. So when you build with `--base /test`, the Webserver searches for `/test/...` file.
You need this for github, because your example gets deployed to a subdirectory.

To test this locally, you'll have to e. G. Rename your build directory `docs` to `<dirname of - - base>` and run the server on the directory above. Then you open the `http://localhost:.../<dir>/` and it should load the resources correctly.

Sorry, that explanation is not really readable. I'll try again, with a simple example.

**Reply by nobkd** [reply]
@tipiirai do you still have the source code for the todomvc example locally somewhere?

**Reply by bartonhammond** [reply]
@nobkd - I got it working locally w/ that recommendation.  Not sure how to mingle that into the GH pages.

**Reply by nobkd** [reply]
You don't have to, because it automatically is deployed to the subdir.

Just publish as you did before.

Because that it's in a subdir, was the reason you have to add --base and the relaive import in the first place.

**Reply by bartonhammond** [reply]
Thanks @nobkd 

Works!   [https://bartonhammond.github.io/nue-todo/](https://bartonhammond.github.io/nue-todo/)

I used this to build and move to dir
```
rm -rf ./nue-todo
nue build --production --base /nue-todo
cp -r ./.dist/prod ./
mv ./prod ./nue-todo
```

`static.yml` is the file in `/.github/workflows`:
```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './nue-todo'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
