### ISSUE TITLE
Header items dissapear if they do not start with capital letter in site.yaml

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#358]
### Header items dissapear if they do not start with capital letter in site.yaml

1. From starter `simple-blog` edit site.yaml, and alternatively set navigation item, "Emma Bennet" to "emma" or "Emma" and observe that the header item dissapears when it's not capitilised.

```yaml
header:
  navigation:
    - emma Bennet: /
    - Contact: /contact/

footer:
  copyright:
    - © Emma Bennet: /
``` 

### Environment

- OS: OSX
- Nuekit Version: ✓ Nue 1.0.0-beta.2 • Bun 1.1.27
