### ISSUE TITLE
Nue's simplicity is great! But then why YAML over JSON?

### ISSUE THREAD

**Issue by elimisteve** [nuejs/nue#536]
### Is your feature request or improvement related to a problem?

The problem of complexity, yes! YAML is not like JSON, it's a complexity disaster: https://noyaml.com/ .

### Solution you'd like

How about using site.json instead of site.yaml? Same for blog/blog.yaml, etc; let's use .json files, not .yaml.

### Alternatives you've considered

.toml might be a decent choice! It'd be great for simple config, but once you need to nest data structures a bit (like simple-blog's site.yaml does with navigation.header and navigation.footer), it seems like JSON would be a better fit.

### Additional context

Seriously, check out https://noyaml.com/ ! FYI the YAML spec is 5-10x the size of the JSON spec. Given the brilliant simplicity of Nue, it deserves so much better than YAML!

**Comment by nobkd** [comment]
I personally think `yaml` is much easier to write and read, but that's just my opinion. AFAIK `yaml` is a superset of `json`, so you could probably just write `json` in there, if you wanted to..

**Comment by tipiirai** [comment]
Shortly: YAML is for humans, JSON for machines. And many of the issues listed on your link (like the Norway problem) no longer exist — at least on the js-yaml implementation we use. If something, we could think of implementing our custom YAML parser without any of the listed problems. I feel JSON would make Nue configuration more complex, not simpler.

**Comment by tipiirai** [comment]
I agree that Nue deservers something better than the current YAML specification — particularly because Nue gets unwarranted bad rap because of that choice. For that reason I have seriously thought about writing a YAML parser, which only takes the good parts of it and addresses the issues listed in noyaml.com. Should be quite small/straightforward project. Does anyone want to help here?

**Comment by AIABHISHEK** [comment]
> I agree that Nue deservers something better than the current YAML specification — particularly because Nue gets unwarranted bad rap because of that choice. For that reason I have seriously thought about writing a YAML parser, which only takes the good parts of it and addresses the issues listed in noyaml.com. Should be quite small/straightforward project. Does anyone want to help here?

I guess that would be best thing would love help

**Comment by chan27-2** [comment]
this sounds like a super interesting idea can i jump in too

**Comment by elimisteve** [comment]
@AIABHISHEK @chan27-2 I asked Claude to write a parser to parse the specific subset of YAML it seems Nue uses. Here's what it came up with: https://claude.ai/share/b7e555e6-1628-4feb-8634-6cd6364aa2ae

**Comment by tipiirai** [comment]
Glad to see excitement around this! 

For the syntax I primarly wish flexible string handling:

1. Never require string values to be quoted. You could write `my_string: Foo : Bar "baz" and 'whatever'` without issues
2. Same with any nested items. `globals: [ @global ]` would not need quotes

The above would remove all my personal glitches with YAML. I don't really have any other complaitnts about YAML — I actually like it. For the project itself, I'd like to see minimalistic source code. Claude gave a a good starting point, but there's always room for improvement. The code should follow our [rules](https://github.com/nuejs/nue/blob/master/CONTRIBUTING.md#code-style) and perhaps the most important: a super broad test suite would be awesome where one could see how the syntax works.

**Comment by elimisteve** [comment]
CONL looks pretty good and very simple: https://cirw.in/blog/conl

**Comment by tipiirai** [comment]
Are you suggesting that Nue should shift from YAML to CONL — and content authors and other non-technical people would find it easier to work with?

**Comment by elimisteve** [comment]
Nevermind; I'm out. I don't have time to _fully_ explain to @tipiirai why the following aspects of YAML are ridiculous and error-prone, so I'll try to be brief so at least anyone else who sees this understands. I saw that Nue cares about simplicity, which gave me false hope regarding how much common sense its author would have.

> Never require string values to be quoted.

This sounds convenient, but anyone who has been programming for more than a few months should have noticed by now that this leads to parsing ambiguities. In particular, it's not viable if you want bools.

> And many of the issues listed on your link (like the Norway problem) no longer exist — at least on the js-yaml implementation we use.

Then js-yaml isn't a YAML parser.

---

Here are serious, real-world problems with YAML; I've pasted the best parts of noyaml.com here so they're harder to dismiss or ignore:

```
# 🚨 Anyone who uses YAML long enough will eventually get burned when attempting to abbreviate Norway 🚨
# `NO` is parsed as a boolean type, which with the YAML 1.1 spec, there are 22 options to write "true" or "false."
# You have to wrap "NO" in quotes to get the expected result.
NI: Nicaragua
NL: Netherlands
NO: Norway # 💣!

# 🚨 Anyone wondering why their first seven Kubernetes clusters deploy just fine, and the eighth fails? 🚨
- 07
- 08
# Results in
[ 7, "08" ]

# YAML knows that, when you have something that looks like the time of day,
# what you _really_ wanted is the time of seconds since midnight
timeOfDay:
  whatYouWrote: 04:30 # And when you parse this file and serialize it again, you get ...
  whatYouSurelyMeant: 16200 # Have fun debugging this one!
  whatYouShouldHaveWritten: !!str 04:30

...

- The problem with YAML they did one thing well. Shitty boiler plate. Then everyone thought it was a good idea.
	
# 💊 Mega twitter thread of pain

# 👉 https://twitter.com/brunoborges/status/1098472238469111808 👈

# 📢 Mandatory reading 📢
#
# "Today we’re going to look at some general problems with the YAML format"
# 👉 https://arp242.net/yaml-config.html 👈
#
# "We replaced 1,000 lines of YAML with 10 structs and people started contributing again"
# 👉 https://tinyurl.com/lessons-in-over-engineering 👈
#
# "What if you used the same language and tools you use to define your app to define your infrastructure?"
# 👉 https://twitter.com/ellism/status/1008728148131733504 👈
#
# "A YAML file is almost always still 'valid' even if it is trunca"
# 👉 https://twitter.com/colmmacc/status/1057316977457324032 👈
#
# "the bug was that the YAML parser ignored the negative signs ... so negative GPS coordinates became positive ones"
# 👉 https://twitter.com/colmmacc/status/1063470541464461312 👈
#
# "Every YAML parser is a custom YAML parser"
# 👉 https://matrix.yaml.info/valid.html 👈
#
# "There are 63 different ways to write multi-line strings in YAML"
# 👉 https://stackoverflow.com/a/21699210/1094085 👈
#
# "Toolchain version 1.70 is parsed as 1.7"
# 👉 https://github.com/dtolnay/rust-toolchain/issues/112 👈
#
# "StrictYAML Design Justifications"
# 👉 https://hitchdev.com/strictyaml/why/ 👈
	
# 💭 Alternative options and approaches to DevOps (cough yamlops cough) 💭
# - https://media.ccc.de/v/36c3-11172-leaving_legacy_behind
# - https://nickel-lang.org/
# - https://dhall-lang.org/
# - https://cuelang.org/
# - https://jsonnet.org/
# - https://www.youtube.com/watch?v=tl9I-R83lKo
# - https://github.com/xtruder/kubenix/tree/kubenix-2.0/examples/nginx-deployment
# - https://github.com/nin-jin/tree.d
```
